---
title: Introduction aux méthodes ensemblistes
author: |
  Mélina Hillion
  Olivier Meslin
slide-number: true
footer: |
  Méthodes ensemblistes
# uncomment for French presentations:
lang: fr-FR
# for blind readers:
slide-tone: false
# for @olevitt:
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
#multiplex: true
format: 
  onyxia-revealjs:
    output-file: index.html
#onyxia-dark-revealjs:
controls: true
css: custom.css
from: markdown+emoji
---

## Constat: des outils adaptés à la statistique publique {.smaller}

- Des méthodes performantes, flexibles et particulièrement adaptées aux données tabulaires :

  - Classification binaire (ex: emploi/chômage)
    
  - Classification multiclasse (ex: niveau de diplôme)
    
  - Régression (ex: imputation de variables continues)
  
- Pouvant apportant des gains de qualité (précision) et d’efficacité  


## Objectif: Renforcer la boîte à outils du statisticien public {.smaller} 

- Enrichissement méthodologique : 

  - Faciliter l'appropriation de ces méthodes par les statisticiens publics
  - Public cible : Statisticiens maîtrisant l'économétrie "traditionnelle", mais peu familiers du machine learning


. . .

- Démarche : Apporter une compréhension profonde et un savoir-faire pratique :

  - Présentations théoriques détaillées
  - Cas d'usage concrets et reproductibles issus de la statistique publique
  - Notebooks interactifs sur des données ouvertes

    
## Méthodes ensemblistes couvertes

- Présentation rigoureuse et intuitive des méthodes et des implémentations:
  - Arbres de décision (CART);
  - Bagging et forêts aléatoires;
  - Gradient boosting (XGBoost).
  
Trois points d'attention: hyper-paramètres, interprétabilité, mise en oeuvre pratique.

. . .

Projet mené en discussion avec Sébastien Da Veiga (Crest/Ensai)


## Interprétabilité et hyperparamètres

- Démystifier les hyperparamètres : 
  - Description de leur rôle précis dans chaque méthode/algorithme
  - Objectif: aider à ajuster les algorithmes aux problèmes rencontrés
    
- Présentation des méthodes d'interprétabilité et de leurs limites (représentation des arbres, _feature importance_, LIME, valeurs de Shapley).


## Cas d'usage envisagés

Mise en œuvre pratique : faciliter l'appropriation via des tutoriels et notebooks sur données ouvertes.

. . .

- Imputation:
   - Valeurs manquantes dans le recensement (ex: diplôme, présence d'un ascenseur)
   - Salaire horaire net dans la DSN
   
- Repondération des enquêtes

- Data editing (repérage d'incohérences)

- Interpolation spatiale: prédiction des prix immobiliers sur le territoire.




